DROP TABLE IF EXISTS sales_history;
DROP TABLE IF EXISTS partners;

CREATE TABLE partners (
    partner_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    inn VARCHAR(12) NOT NULL,
    email VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    partner_type VARCHAR(64) NOT NULL,
    director VARCHAR(255) NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 0 AND rating <= 10),
    UNIQUE (inn)
);

CREATE TABLE sales_history (
    sale_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id INTEGER NOT NULL REFERENCES partners (partner_id),
    quantity INTEGER NOT NULL CHECK (quantity > 0)
);
