DROP TABLE IF EXISTS shipment_items;
DROP TABLE IF EXISTS shipments;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;

CREATE TABLE partners (
    partner_id  INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255)    NOT NULL,
    inn         VARCHAR(12)     NOT NULL,
    email       VARCHAR(255)    NOT NULL,
    address     VARCHAR(500)    NOT NULL,
    phone       VARCHAR(20)     NOT NULL,
    CONSTRAINT pk_partners PRIMARY KEY (partner_id),
    CONSTRAINT uq_partners_inn UNIQUE (inn),
    CONSTRAINT uq_partners_email UNIQUE (email)
);

CREATE TABLE products (
    product_id    INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    product_code  VARCHAR(20)     NOT NULL,
    name          VARCHAR(255)    NOT NULL,
    price         DECIMAL(10, 2)  NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT uq_products_product_code UNIQUE (product_code),
    CONSTRAINT chk_products_price CHECK (price >= 0)
);

CREATE TABLE orders (
    order_id          INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    partner_id        INTEGER      NOT NULL,
    product_id        INTEGER      NOT NULL,
    contract_number   VARCHAR(50)  NOT NULL,
    contract_date     DATE         NOT NULL,
    planned_quantity  INTEGER      NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_partner
        FOREIGN KEY (partner_id) REFERENCES partners (partner_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_orders_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_orders_planned_quantity CHECK (planned_quantity > 0)
);

CREATE TABLE shipments (
    shipment_id    INTEGER  GENERATED BY DEFAULT AS IDENTITY,
    shipment_date  DATE     NOT NULL,
    CONSTRAINT pk_shipments PRIMARY KEY (shipment_id)
);

CREATE TABLE shipment_items (
    shipment_item_id  INTEGER  GENERATED BY DEFAULT AS IDENTITY,
    shipment_id       INTEGER  NOT NULL,
    order_id          INTEGER  NOT NULL,
    quantity_shipped  INTEGER  NOT NULL,
    CONSTRAINT pk_shipment_items PRIMARY KEY (shipment_item_id),
    CONSTRAINT fk_shipment_items_shipment
        FOREIGN KEY (shipment_id) REFERENCES shipments (shipment_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_shipment_items_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_shipment_items_quantity CHECK (quantity_shipped > 0)
);

CREATE INDEX idx_orders_partner_id ON orders (partner_id);
CREATE INDEX idx_orders_product_id ON orders (product_id);
CREATE INDEX idx_shipment_items_shipment_id ON shipment_items (shipment_id);
CREATE INDEX idx_shipment_items_order_id ON shipment_items (order_id);

COMMENT ON TABLE partners IS 'Партнёры (заказчики)';
COMMENT ON TABLE products IS 'Товары (номенклатура завода)';
COMMENT ON TABLE orders IS 'Заказы на поставку товаров партнёрам';
COMMENT ON TABLE shipments IS 'Заголовки отгрузок (накладные)';
COMMENT ON TABLE shipment_items IS 'Строки отгрузки: связь отгрузки с заказом и количеством';

COMMENT ON COLUMN partners.partner_id IS 'Идентификатор партнёра';
COMMENT ON COLUMN partners.name IS 'Наименование заказчика';
COMMENT ON COLUMN partners.inn IS 'ИНН партнёра (уникальный)';
COMMENT ON COLUMN partners.email IS 'Контактный email (уникальный)';
COMMENT ON COLUMN partners.address IS 'Адрес';
COMMENT ON COLUMN partners.phone IS 'Телефон';

COMMENT ON COLUMN products.product_id IS 'Идентификатор товара';
COMMENT ON COLUMN products.product_code IS 'Код товара';
COMMENT ON COLUMN products.name IS 'Наименование товара';
COMMENT ON COLUMN products.price IS 'Цена (тыс. руб.)';

COMMENT ON COLUMN orders.order_id IS 'Код заказа';
COMMENT ON COLUMN orders.partner_id IS 'Партнёр-заказчик';
COMMENT ON COLUMN orders.product_id IS 'Заказанный товар';
COMMENT ON COLUMN orders.contract_number IS 'Номер договора';
COMMENT ON COLUMN orders.contract_date IS 'Дата заключения договора';
COMMENT ON COLUMN orders.planned_quantity IS 'Плановая поставка (шт.)';

COMMENT ON COLUMN shipments.shipment_id IS 'Код отгрузки';
COMMENT ON COLUMN shipments.shipment_date IS 'Дата отгрузки';

COMMENT ON COLUMN shipment_items.shipment_item_id IS 'Идентификатор строки отгрузки';
COMMENT ON COLUMN shipment_items.shipment_id IS 'Ссылка на отгрузку';
COMMENT ON COLUMN shipment_items.order_id IS 'Ссылка на заказ';
COMMENT ON COLUMN shipment_items.quantity_shipped IS 'Отгружено (шт.)';
